services:
  qr-code-generator-backend:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - CACHE_EXPIRATION_TIME=${CACHE_EXPIRATION_TIME}
      - MAX_CACHE_SIZE=${MAX_CACHE_SIZE}
    env_file:
      - .env